dateModified: 1622902673
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SENDER_NAME
  replyToEmail: $REPLY_TO_EMAIL
  template: null
  transportSettings:
    encryptionMethod: tls
    host: $GMAIL_HOSTNAME
    password: $GMAIL_PASSWORD
    port: $GMAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $GMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  cloudflare:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      apiKey: $CLOUDFLARE_API_KEY
      apiToken: null
      authType: key
      email: $CLOUDFLARE_ACCOUNT_EMAIL
      purgeElements:
        - craft\elements\Asset
        - craft\elements\Category
        - craft\elements\Entry
        - craft\elements\Tag
      userServiceKey: ''
      zone: $CLOUDFLARE_ZONE_ID
      zoneName: null
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 9IGMRK2MX1DX7BWLDICIIZ91
    schemaVersion: 1.1.9
  jitter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  lightkeeper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      advancedSettings: false
      anonymous: false
      clsThreshold: '0.1'
      compact: false
      developerEmail: null
      fcpThreshold: '2000'
      fidThreshold: '100'
      lcpThreshold: '2500'
      minimumAccessibility: '100'
      minimumBestPractices: '100'
      minimumPerformance: '90'
      minimumSeo: '100'
      ttfbThreshold: '600'
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  read-time:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    licenseKey: HDCAS6CQHSWMR6JKR3UTIUG7
    schemaVersion: 3.0.9
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  splash:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
